app:
  name: 
http:
  mode: debug
  # mode: release
  host: 127.0.0.1
  port: 7779
  graphqlPath: graphql
  playgroundPath: playground
  isPlaygroundEnabled: true
  allowOrigins:
    - "*"
  allowMethods: 
    - "PUT"
    - "GET"
    - "POST"
    - "HEAD"
    - "PATCH"
    - "OPTIONS"
    - "DELETE"
  allowHeaders:
    - "*"
db:
  dialect: mysql
  user: root
  password: ""
  host: "127.0.0.1"
  port: 3306
  name: 
  charset: utf8mb4
log:
  filename: /tmp/.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
  level: "debug"
  stdout: false
jaeger:
  serviceName: admin
  reporter:
    localAgentHostPort: "jaeger-agent:6831"
  sampler:
    type: const
    param: 1
jwt:
  # dd if=/dev/urandom bs=1 count=32 2>/dev/null | base64 -w 0 | rev | cut -b 2- | rev
  # signingKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  signingKey: YOUCHENG
  issuer: ycheng.pro
  claimKey: claim
  signingMethod: HS512
  # seconds
  expired: 1000000
casbin:
  policy: "configs/rbac_model.conf"
